[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish= "build/"

[context.deploy-preview.environment]
  REACT_APP_API_HOST = "http://localhost:4003/api"

[context.branch-deploy.environment]
   REACT_APP_API_HOST = "http://localhost:4003/api"
