export const ON_START_CREATING_DECK = 'ON_START_CREATING_DECK';
export const ON_DECK_CREATION_CANCELLED = 'ON_DECK_CREATION_CANCELLED';
export const ON_DECK_CREATION_COMPLETE = 'ON_DECK_CREATION_COMPLETE';
export const ON_SEND_DECK = 'ON_SEND_DECK';

export const ON_START_FETCHING_DECKS = 'ON_START_FETCHING_DECKS';
export const ON_GET_DECKS_CANCELLED = 'ON_GET_DECKS_CANCELLED';
export const ON_GET_DECKS_COMPLETE = 'ON_GET_DECKS_COMPLETE';

export const ON_START_CREATING_CARD = 'ON_START_CREATING_CARD';
export const ON_CARD_CREATION_CANCELLED = 'ON_CARD_CREATION_CANCELLED';
export const ON_CARD_CREATION_COMPLETE = 'ON_CARD_CREATION_COMPLETE';
export const ON_SEND_CARD = 'ON_SEND_CARD';

export const ON_START_FETCHING_TAGS = 'ON_START_FETCHING_TAGS';
export const ON_DECK_TAGS_FETCH_FAILED = 'ON_DECK_TAGS_FETCH_FAILED';
export const ON_DECK_TAGS_FETCH_SUCCESS = 'ON_DECK_TAGS_FETCH_SUCCESS';

export const SET_SELECTED_TAGS = 'SET_SELECTED_TAGS';
export const CLEAR_SELECTED_TAGS = 'CLEAR_SELECTED_TAGS';
