const ON_BEGIN_PROFILE_FETCH = 'ON_BEGIN_PROFILE_FETCH';
const ON_PROFILE_FETCH_SUCCESS = 'ON_PROFILE_FETCH_SUCCESS';
const ON_PROFILE_FETCH_FAILED = 'ON_PROFILE_FETCH_FAILED';

const ON_START_CREATING_DECK = 'ON_START_CREATING_DECK';
const ON_DECK_CREATION_CANCELLED = 'ON_DECK_CREATION_CANCELLED';
const ON_DECK_CREATION_COMPLETE = 'ON_DECK_CREATION_COMPLETE';
const ON_SEND_DECK = 'ON_SEND_DECK';

const ON_START_CREATING_CARD = 'ON_START_CREATING_CARD';
const ON_CARD_CREATION_CANCELLED = 'ON_CARD_CREATION_CANCELLED';
const ON_CARD_CREATION_COMPLETE = 'ON_CARD_CREATION_COMPLETE';
const ON_SEND_CARD = 'ON_SEND_CARD';

const ON_START_FETCHING_TAGS = 'ON_START_FETCHING_TAGS';
const ON_DECK_TAGS_FETCH_FAILED = 'ON_DECK_TAGS_FETCH_FAILED';
const ON_DECK_TAGS_FETCH_SUCCESS = 'ON_DECK_TAGS_FETCH_SUCCESS';

const SET_SELECTED_TAGS = 'SET_SELECTED_TAGS';
const CLEAR_SELECTED_TAGS = 'CLEAR_SELECTED_TAGS';

const ON_START_FETCHING_CARDS = 'ON_START_FETCHING_CARDS';
const ON_DECK_CARDS_FETCH_FAILED = 'ON_DECK_CARDS_FETCH_FAILED';
const ON_DECK_CARDS_FETCH_SUCCESS = 'ON_DECK_CARDS_FETCH_SUCCESS';

const ON_SELECT_DECK = 'ON_SELECT_DECK';
const ON_GET_SINGLE_DECK_SUCCESS = 'ON_GET_SINGLE_DECK_SUCCESS';
const ON_GET_SINGLE_DECK_FAILED = 'ON_GET_SINGLE_DECK_FAILED';

export default {
  ON_BEGIN_PROFILE_FETCH,
  ON_PROFILE_FETCH_SUCCESS,
  ON_PROFILE_FETCH_FAILED,

  ON_DECK_CREATION_CANCELLED,
  ON_DECK_CREATION_COMPLETE,
  ON_START_CREATING_DECK,
  ON_SEND_DECK,

  ON_START_FETCHING_TAGS,
  ON_DECK_TAGS_FETCH_FAILED,
  ON_DECK_TAGS_FETCH_SUCCESS,

  ON_CARD_CREATION_CANCELLED,
  ON_CARD_CREATION_COMPLETE,
  ON_START_CREATING_CARD,
  ON_SEND_CARD,

  SET_SELECTED_TAGS,
  CLEAR_SELECTED_TAGS,

  ON_DECK_CARDS_FETCH_FAILED,
  ON_DECK_CARDS_FETCH_SUCCESS,
  ON_START_FETCHING_CARDS,

  ON_SELECT_DECK,
  ON_GET_SINGLE_DECK_SUCCESS,
  ON_GET_SINGLE_DECK_FAILED,
};
