const ON_BEGIN_PROFILE_FETCH = 'ON_BEGIN_PROFILE_FETCH';
const ON_PROFILE_FETCH_SUCCESS = 'ON_PROFILE_FETCH_SUCCESS';
const ON_PROFILE_FETCH_FAILED = 'ON_PROFILE_FETCH_FAILED';
const ON_START_CREATING_DECK = 'ON_START_CREATING_DECK';
const ON_DECK_CREATION_CANCELLED = 'ON_DECK_CREATION_CANCELLED';
const ON_DECK_CREATION_COMPLETE = 'ON_DECK_CREATION_COMPLETE';
const ON_START_FETCHING_TAGS = 'ON_START_FETCHING_TAGS';
const ON_DECK_TAGS_FETCH_FAILED = 'ON_DECK_TAGS_FETCH_FAILED';
const ON_DECK_TAGS_FETCH_SUCCESS = 'ON_DECK_TAGS_FETCH_SUCCESS';

export default {
  ON_BEGIN_PROFILE_FETCH,
  ON_DECK_CREATION_CANCELLED,
  ON_DECK_CREATION_COMPLETE,
  ON_DECK_TAGS_FETCH_FAILED,
  ON_DECK_TAGS_FETCH_SUCCESS,
  ON_START_CREATING_DECK,
  ON_START_FETCHING_TAGS,
  ON_PROFILE_FETCH_SUCCESS,
  ON_PROFILE_FETCH_FAILED,
};
